pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = "Gegy"
            url = uri("https://maven.gegy.dev")
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
